name = "miss-ewe"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"

[env.production]
route = "mrstyx.com/miss-ewe/*"
